services:
    noir-core:
        image: noir-core
        container_name: noir-core
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
        volumes:
            - $PWD/resources:/resources
        env_file:
            - .env
        networks:
            - noir

    noir-app:
        image: noir-app
        container_name: noir-app
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - $PWD/resources:/resources
            - /dev:/dev
        env_file:
            - .env
        privileged: true
        network_mode: host
        restart: unless-stopped

    noir-mongo:
        image: mongo:8.0.16
        container_name: noir-mongo
        ports:
            - "27017:27017"
        command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]
        volumes:
            - $PWD/resources/db/mongo/db:/data/db:z
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 320M
        restart: unless-stopped
        networks:
            - noir

networks:
    noir:
        name: noir
        driver: bridge
