services:
    noir-devcontainer:
        image: noir-devcontainer
        container_name: noir-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
        env_file:
            - ../.env
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - noir

networks:
    noir:
        name: noir
        driver: bridge
